name: dju_parking_project
description: "대전대학교 주차장 앱"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.1.0
  http: ^0.13.6
  flutter_native_splash: ^2.4.6
  flutter_material_design_icons: ^1.1.7447
  intl: ^0.18.0
  dropdown_button2: ^2.3.9
  jwt_decoder: ^2.0.1
  mailer: ^6.2.5
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  tosspayments_widget_sdk_flutter: ^2.1.2
  flutter_inappwebview: any
  url_launcher: any
  kakao_flutter_sdk_user: ^1.9.1
  video_player: ^2.10.0

  # ★ 1. (수정) ★
  # video_player를 'flutter_launcher_icons:'가 아닌,
  # 'dependencies:' 섹션의 *이곳*으로 옮겼습니다.
  #video_player: ^2.8.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/splash/splash_logo.png

    # ★ 2. (추가) ★
    # ViewParkingCam.dart가 'camera_error.png'를
    # 로드할 수 있도록 'assets/images/' 경로를 추가했습니다.
    - assets/images/

    - .env

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Thin.otf
          weight: 100
        - asset: assets/fonts/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 600

    - family: VitroPride
      fonts:
        - asset: assets/fonts/VITRO_PRIDE_OTF.otf

    - family: VitroCore
      fonts:
        - asset: assets/fonts/VITRO_CORE_OTF.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  # ★ (삭제) ★
  # 'video_player: ^2.8.6'를 이곳에서 삭제했습니다.